import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { checkCompilation } from "../dist/build/check.js";
import { compileCatalogue } from "../dist/build/compile.js";
import { writeCompilation } from "../dist/build/transaction.js";
import { loadConfig } from "../dist/config/load.js";
import { parseManifest } from "../dist/registry/manifest.js";
import {
  createFixture,
  removeFixture,
  repositoryRoot,
  validEntrySource,
} from "./helpers/fixture.js";

test("build renders deterministic fragments, resolves id links, and checks committed bytes", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const first = await compileCatalogue(config);
  await writeCompilation(first, config);
  checkCompilation(await compileCatalogue(config), config);
  const home = await fs.promises.readFile(
    path.join(fixture.mockupsDir, "screens/home.mobile.html"),
    "utf8",
  );
  assert.match(home, /href="\.\/details\.mobile\.html"/);
  assert.equal(home.includes(fixture.root), false);
  const second = await compileCatalogue(config);
  assert.deepEqual([...second.outputs], [...first.outputs]);
});

test("custom renderer shares consumer React context and injects collected styles", async () => {
  const config = await loadConfig(
    repositoryRoot,
    "examples/basic/mokabook.config.ts",
  );
  const compilation = await compileCatalogue(config);
  const mobile = compilation.outputs.get("screens/welcome.mobile.html") ?? "";
  assert.match(mobile, /data-example-renderer="mobile"/);
  assert.match(mobile, /<style>body\{margin:0\}<\/style>/);
  assert.equal(mobile.includes(repositoryRoot), false);
});

test("manifest readers accept version 2 only through explicit compatibility", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const legacy = {
    ...compilation.manifest,
    generatedBy: undefined,
    schemaVersion: 2,
  };
  assert.throws(() => parseManifest(legacy), /schema version 3/);
  assert.equal(parseManifest(legacy, true).schemaVersion, 3);
});

test("check groups missing, stale, and proven orphan output", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  await writeCompilation(compilation, config);
  await fs.promises.rm(
    path.join(fixture.mockupsDir, "screens/home.mobile.html"),
  );
  await fs.promises.writeFile(
    path.join(fixture.mockupsDir, "screens/home.desktop.html"),
    "stale\n",
  );
  await fs.promises.writeFile(
    path.join(fixture.mockupsDir, "orphan.html"),
    "<!-- Generated by mokabook from entries/old.mockup.tsx. Do not edit. -->\n<html></html>\n",
  );
  assert.throws(
    () => checkCompilation(compilation, config),
    /missing generated files[\s\S]*stale generated files[\s\S]*orphan generated files/,
  );
});

test("invalid source leaves every last-good generated byte unchanged", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  await writeCompilation(await compileCatalogue(config), config);
  const before = await treeDigest(fixture.mockupsDir);
  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource({ body: `<a href="mock:missing-screen">Broken</a>` }),
  );
  await assert.rejects(
    () => compileCatalogue(config),
    /unknown id: missing-screen/,
  );
  assert.equal(await treeDigest(fixture.mockupsDir), before);
});

test("registry rejects duplicate ids, broken relationships, and fragment collisions", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace('id: "details"', 'id: "home"'),
  );
  const config = await loadConfig(fixture.root);
  await assert.rejects(() => compileCatalogue(config), /duplicate-id/);

  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace("screens/details.html", "screens/home.html"),
  );
  await assert.rejects(() => compileCatalogue(config), /duplicate-route/);

  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace(
      'useCaseIds: ["tour"]',
      'useCaseIds: ["missing"]',
    ),
  );
  await assert.rejects(() => compileCatalogue(config), /missing-use-case/);

  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace(
      "screens/details.html",
      "screens/home.mobile.html",
    ),
  );
  await assert.rejects(
    () => compileCatalogue(config),
    /fragment route collides/,
  );

  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace("screens/details.html", "../details.html"),
  );
  await assert.rejects(() => compileCatalogue(config), /invalid-route/);
});

test("registry reports malformed relationship arrays without leaking a TypeError", async (context) => {
  const fixture = await createFixture(`
import { defineCollection } from "mokabook";
export const mockups = [defineCollection({
  childIds: null as unknown as string[],
  dependencies: [],
  description: "Malformed collection",
  id: "malformed",
  navPath: [],
  relatedDocs: [],
  title: "Malformed"
})];
`);
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  await assert.rejects(
    () => compileCatalogue(config),
    /childIds must be a non-empty array of strings/,
  );
});

test("link validation fails closed for missing anchors and escaping paths", async (context) => {
  const fixture = await createFixture(
    validEntrySource({
      body: `<a href="details.mobile.html#absent">Broken anchor</a>`,
    }),
  );
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  await assert.rejects(() => compileCatalogue(config), /missing target anchor/);
  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource({ body: `<a href="../../../outside.html">Escape</a>` }),
  );
  await assert.rejects(() => compileCatalogue(config), /escapes mockupsDir/);
  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource({ body: `<a href="missing.html">Missing</a>` }),
  );
  await assert.rejects(() => compileCatalogue(config), /missing target/);
  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource({
      body: `<a href="./details.html">Logical route only</a>`,
    }),
  );
  await assert.rejects(() => compileCatalogue(config), /missing target/);
});

test("missing declared dependencies and stylesheets are actionable", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replaceAll('"notes.md"', '"missing.md"'),
  );
  await assert.rejects(
    () => compileCatalogue(config),
    /path does not exist: missing.md/,
  );
  await fs.promises.writeFile(fixture.entryPath, validEntrySource());
  await fs.promises.writeFile(
    fixture.configPath,
    `export default { entriesDir: "entries", mockupsDir: "mockups", repoRoot: ".", stylesheets: [{ match: "**/*.html", stylesheets: ["missing.css"] }] };\n`,
  );
  const stylesheetConfig = await loadConfig(fixture.root);
  await assert.rejects(
    () => compileCatalogue(stylesheetConfig),
    /stylesheet does not exist/,
  );
});

test("writer refuses to overwrite an unowned route", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const target = path.join(fixture.mockupsDir, "screens/home.mobile.html");
  await fs.promises.mkdir(path.dirname(target), { recursive: true });
  await fs.promises.writeFile(target, "user-authored\n");
  await assert.rejects(
    () => writeCompilation(compilation, config),
    /refusing to overwrite unowned/,
  );
  assert.equal(await fs.promises.readFile(target, "utf8"), "user-authored\n");
});

test("generic legacy TypeScript sources coexist through explicit config", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const pages = path.join(fixture.root, "legacy");
  await fs.promises.mkdir(pages);
  await fs.promises.writeFile(
    path.join(pages, "old.source.ts"),
    `export const source = () => "<!doctype html><html><body><main id=old>Legacy</main></body></html>";\n`,
  );
  await fs.promises.writeFile(
    fixture.configPath,
    `export default { entriesDir: "entries", legacy: { pagesDir: "legacy", routeAliases: { "old.source.ts": "archive/old.html" }, lint: { maxScreensPerPage: 5 } }, mockupsDir: "mockups", repoRoot: "." };\n`,
  );
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  assert.ok(compilation.outputs.has("archive/old.html"));
  await writeCompilation(compilation, config);
  checkCompilation(await compileCatalogue(config), config);
});

test("legacy HTML component expansion and opt-in lints stay consumer-configured", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const pages = path.join(fixture.root, "legacy");
  await fs.promises.mkdir(pages);
  await fs.promises.writeFile(
    path.join(pages, "components.tsx"),
    `export function renderComponent(name: string, attributes: Record<string, string>) { return name === "notice" ? <aside id="notice">{attributes.label}</aside> : ""; }\n`,
  );
  await fs.promises.writeFile(
    path.join(pages, "old.source.html"),
    `<!doctype html><html><body data-mokabook-screen><!-- @mokabook/component notice label="Expanded" --></body></html>\n`,
  );
  await fs.promises.writeFile(
    fixture.configPath,
    `export default { entriesDir: "entries", legacy: { pagesDir: "legacy", components: "legacy/components.tsx", lint: { maxScreensPerPage: 1 } }, mockupsDir: "mockups", repoRoot: "." };\n`,
  );
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  assert.match(
    compilation.outputs.get("old.html") ?? "",
    /<aside id="notice">Expanded<\/aside>/,
  );
  await fs.promises.writeFile(
    path.join(pages, "old.source.html"),
    `<!doctype html><html><body><main data-mokabook-screen></main><main data-mokabook-screen></main></body></html>\n`,
  );
  await assert.rejects(
    () => compileCatalogue(config),
    /configured maximum is 1/,
  );
});

async function treeDigest(root: string): Promise<string> {
  const files = await listFiles(root);
  const hash = crypto.createHash("sha256");
  for (const file of files) {
    hash.update(path.relative(root, file));
    hash.update(await fs.promises.readFile(file));
  }
  return hash.digest("hex");
}

async function listFiles(root: string): Promise<string[]> {
  const entries = await fs.promises.readdir(root, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const candidate = path.join(root, entry.name);
      return entry.isDirectory() ? listFiles(candidate) : [candidate];
    }),
  );
  return files.flat().sort();
}
