import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { compileCatalogue } from "../dist/build/compile.js";
import { isOwned } from "../dist/build/ownership.js";
import { loadConfig } from "../dist/config/load.js";
import {
  createFixture,
  removeFixture,
  validEntrySource,
} from "./helpers/fixture.js";

test("generated ownership belongs only to configured source roots", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const foreign = path.join(fixture.mockupsDir, "foreign.html");
  const deleted = path.join(fixture.mockupsDir, "deleted.html");
  await fs.promises.writeFile(
    foreign,
    "<!-- Generated by mokabook from another-catalogue/page.mockup.tsx. Do not edit. -->\n<html></html>\n",
  );
  await fs.promises.writeFile(
    deleted,
    "<!-- Generated by mokabook from entries/deleted.mockup.tsx. Do not edit. -->\n<html></html>\n",
  );

  assert.equal(isOwned(foreign, config), false);
  assert.equal(isOwned(deleted, config), true);
});

test("build rejects non-canonical repository dependency paths", async (context) => {
  const source = validEntrySource().replaceAll(
    'dependencies: ["notes.md"]',
    'dependencies: ["docs/../notes.md"]',
  );
  const fixture = await createFixture(source);
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);

  await assert.rejects(
    () => compileCatalogue(config),
    /dependencies path must be a safe repository-relative path/,
  );
});
