import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { ReactNode } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { build } from "esbuild";
import { concepts } from "../src/concepts.js";
import { ReviewGallery } from "../src/pages/index.source.js";
import { FieldnotesScreen } from "../src/pages/website/fieldnotes/index.source.js";
import { SignalScreen } from "../src/pages/website/signal/index.source.js";
import { CommonGroundScreen } from "../src/pages/website/common-ground/index.source.js";

const root = fileURLToPath(new URL("../", import.meta.url));
const repositoryRoot = resolve(root, "../..");
const check = process.argv.includes("--check");
const unknown = process.argv
  .slice(2)
  .filter((argument) => argument !== "--check");
if (unknown.length) throw new Error(`Unknown options: ${unknown.join(", ")}`);

interface Page {
  path: string;
  title: string;
  description: string;
  styles: string[];
  content: ReactNode;
}

const pages: Page[] = [
  {
    path: "index.html",
    title: "Mokabook — website directions",
    description:
      "Compare three Mokabook website directions on desktop and mobile.",
    styles: ["gallery"],
    content: <ReviewGallery />,
  },
  {
    path: concepts[0].path,
    title: "Mokabook — get on the same page",
    description:
      "Give your next product idea a place to take shape, with real screens and your own components.",
    styles: ["product", "fieldnotes"],
    content: <FieldnotesScreen />,
  },
  {
    path: concepts[1].path,
    title: "Mokabook — less guesswork, more good product",
    description: "Give the next change a clearer picture of what to build.",
    styles: ["product", "signal"],
    content: <SignalScreen />,
  },
  {
    path: concepts[2].path,
    title: "Mokabook — great products start on common ground",
    description: "Bring the idea, the details, and the conversation together.",
    styles: ["product", "common-ground"],
    content: <CommonGroundScreen />,
  },
];

const font = await readFile(
  resolve(repositoryRoot, "src/server/shell/assets/fonts/InterVariable.woff2"),
);
const license = await readFile(
  resolve(repositoryRoot, "src/server/shell/assets/fonts/Inter-OFL.txt"),
  "utf8",
);
const fontCss = `@font-face{font-family:Inter;font-style:normal;font-weight:100 900;font-display:swap;src:url(data:font/woff2;base64,${font.toString("base64")}) format('woff2')}`;
const script = await build({
  entryPoints: [resolve(root, "src/browser.ts")],
  bundle: true,
  write: false,
  format: "iife",
  minify: true,
  target: "es2022",
  legalComments: "none",
});
const scriptText = script.outputFiles[0]?.text;
if (!scriptText) throw new Error("The mockup browser script was not built.");

for (const page of pages) {
  const styles = await Promise.all(
    ["base", ...page.styles].map((name) =>
      readFile(resolve(root, `src/styles/${name}.css`), "utf8"),
    ),
  );
  const css = await build({
    stdin: {
      contents: styles.join("\n"),
      resolveDir: resolve(root, "src/styles"),
      loader: "css",
    },
    bundle: true,
    minify: true,
    write: false,
  });
  const cssText = css.outputFiles[0]?.text;
  if (!cssText) throw new Error(`Styles for ${page.path} were not built.`);
  const markup = renderToStaticMarkup(
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={page.description} />
        <meta name="robots" content="noindex, nofollow" />
        <title>{page.title}</title>
        <link
          rel="icon"
          href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%2364774d'/%3E%3Cpath d='M7 8l9 3 9-3v16l-9 2-9-2zm9 3v15' fill='none' stroke='%23fff' stroke-width='2'/%3E%3C/svg%3E"
        />
        <style dangerouslySetInnerHTML={{ __html: fontCss + cssText }} />
      </head>
      <body>
        {page.content}
        <script dangerouslySetInnerHTML={{ __html: scriptText }} />
      </body>
    </html>,
  );
  const html = `<!doctype html>\n<!-- Generated by npm run mockups:build. Edit docs/mockups/src.\nEmbedded Inter font license:\n${license.replaceAll("--", "—")}\n-->\n${markup}\n`;
  const destination = resolve(root, page.path);
  if (check) {
    const actual = await readFile(destination, "utf8");
    if (actual !== html)
      throw new Error(`${page.path} is stale. Run npm run mockups:build.`);
  } else {
    await mkdir(dirname(destination), { recursive: true });
    await writeFile(destination, html);
  }
  process.stdout.write(`${check ? "Checked" : "Built"} ${page.path}\n`);
}
